# Generated by Django 2.2.7 on 2019-11-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=10)),
                ('lName', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
