# Generated by Django 2.2.7 on 2019-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0002_auto_20191124_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=80)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
