# Generated by Django 2.2.7 on 2019-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=20)),
                ('display', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=80)),
                ('memory', models.CharField(max_length=20)),
                ('mainCam', models.CharField(max_length=50)),
                ('selfieCam', models.CharField(max_length=80)),
                ('phfeatures', models.CharField(max_length=20)),
                ('battery', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=80)),
            ],
        ),
    ]
