# Generated by Django 2.2.7 on 2019-11-30 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
