# Generated by Django 2.2.7 on 2019-12-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0007_spec_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='C_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Email',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='battery',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='body',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='cpu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='display',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='mainCam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='memory',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='network',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='phfeatures',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='platform',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='price',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='selfieCam',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fName',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lName',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
