# Generated by Django 2.2.7 on 2019-12-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0008_auto_20191201_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specid', models.CharField(max_length=50, null=True)),
                ('comments', models.CharField(max_length=50, null=True)),
                ('userid', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
