# Generated by Django 2.2.7 on 2019-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userid',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
