# Generated by Django 2.2.7 on 2019-12-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0011_comment_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='companyid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
