# Generated by Django 2.2.7 on 2019-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0012_spec_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
