# Generated by Django 2.2.7 on 2020-01-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEKBUUDY', '0013_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajeesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lsname', models.CharField(max_length=10)),
            ],
        ),
    ]
